### PR TITLE
Update zindex function

### PR DESCRIPTION
**Pull request by pigeonfresh**
Make list an optional property by setting a default and replacing the warning with an actual error

### CODE REVIEW

**Comment by ThaNarie** [comment]
Do we often use multiple lists, and if so, do we ever re-use element-names in those different lists?

If both are true, this could result in accidental wrong z-indexes, and might be a consideration to not make the list param optional.

Otherwise fine :D

**Comment by pigeonfresh** [comment]
I usually have one list for the 'global' UI elements (popups, video-overlays, sticky headers, notifications etc). And sometime I use a list inside my component's stylesheet for ordering elements within that component. So in my case it's always the default list (unless specified).

**Comment by ThaNarie** [comment]
That doesn't answer the second part :D

> do we ever re-use element-names in those different lists

**Comment by pigeonfresh** [comment]
Well in theory it's possible to mix up names by accident. Apparently specifying a list is considered a safety net. I will close this PR.

**Comment by ThaNarie** [comment]
> Apparently specifying a list is considered a safety net
I'm just asking some questions you might not have considered. Based on your experience (which I don't have) you can make the best decision :)

If it's only a theoretical scenario, but would almost never happen in practise, the practical convenience would outweigh the potential theoretical risk :) So the changes in this PR would be useful.

So I hope this is closed for the right reasons; your own conclusion :)

**Pull request closed without merging**
